<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SCEWIN_Studio</AssemblyName>
    <RootNamespace>SCEWIN_Studio</RootNamespace>
    <Platforms>x64;AnyCPU</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\app_icon.ico" />
    <Resource Include="Resources\app_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\SCEWIN.zip" />
    <EmbeddedResource Include="Resources\Strings.ru.json">
      <LogicalName>SCEWIN_Studio.Resources.Strings.ru.json</LogicalName>
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Strings.en.json">
      <LogicalName>SCEWIN_Studio.Resources.Strings.en.json</LogicalName>
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
    <Content Include="Resources\SCEWIN.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Strings.ru.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Strings.en.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
